#!/usr/bin/env bash
PWD=`pwd`

HOST_NEO4J_EXTENSION_SCRIPTS="$PWD/neo4j/scripts"
HOST_NEO4J_BLANKDBPATH="$PWD/neo4j/blank-db"
NEO4J_EXTENSION_PATH="/opt/neo4j-extension"
NEO4J_GRAPHNAME="neo4j"
NEO4J_BACKUPPATH="/opt/db-backups"
NEO4J_BLANKDBPATH="/opt/blank-db"
NEO4J_USER="neo4j"

docker run -itd -v $HOST_NEO4J_EXTENSION_SCRIPTS:$NEO4J_EXTENSION_PATH \
-v $HOST_NEO4J_BLANKDBPATH:$NEO4J_BLANKDBPATH \
-e NEO4J_EXTENSION_PATH=$NEO4J_EXTENSION_PATH \
-e NEO4J_GRAPHNAME=$NEO4J_GRAPHNAME -e NEO4J_BACKUPPATH=$NEO4J_BACKUPPATH \
-e NEO4J_BLANKDBPATH=$NEO4J_BLANKDBPATH -e NEO4J_USER=$NEO4J_USER \
-p 7474:7474 -p 7687:7687 \
--network=my-bridge-network-dd --name=neo4j \
duediligence-neo4j
